using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerAnimator : MonoBehaviour
{
    [Header(" Elements ")]
    [SerializeField] private Animator animator;
    [SerializeField] private ParticleSystem waterParticles;

    [Header(" Settings ")]
    [SerializeField] private float moveSpeedMultiplier;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void ManageAnimations(Vector3 moveVector)
    {
        if(moveVector.magnitude > 0)
        {
            animator.SetFloat("moveSpeed", moveVector.magnitude * moveSpeedMultiplier);
            PlayRunAnimation();

            animator.transform.forward = moveVector.normalized;
        }
        else
        {
            PlayIdleAnimation();
        }
    }

    private void PlayRunAnimation()
    {
        animator.Play("Run");
    }

    private void PlayIdleAnimation()
    {
        animator.Play("Idle");
    }

    public void PlaySowAnimation()
    {
        animator.SetLayerWeight(1, 1);
    }

    public void StopSowAnimation()
    {
        animator.SetLayerWeight(1, 0);
    }

    public void PlayWaterAnimation()
    {
        animator.SetLayerWeight(2, 1);
    }

    public void StopWaterAnimation()
    {
        animator.SetLayerWeight(2, 0);
        waterParticles.Stop();
    }

    public void PlayHarvestAnimation()
    {
        animator.SetLayerWeight(3, 1);
    }

    public void StopHarvestAnimation()
    {
        animator.SetLayerWeight(3, 0);
    }

    public void PlayShakeTreeAnimation()
    {
		animator.SetLayerWeight(4, 1);
        animator.Play("Shake Tree");
	}

	public void StopShakeTreeAnimation()
	{
		animator.SetLayerWeight(4, 0);
	}
}
